#!/bin/bash
#PBS -m ea
#PBS -N {jobname}
#PBS -M {email}
#PBS -W group_list={group_list}
#PBS -q standard
#PBS -l select=1:ncpus=28:mem=168gb:pcmem=6gb
#PBS -l cput={cput}:0:0
#PBS -l walltime={walltime}:0:0

cd {mg5_process_dir}
rm *.e* *.o*
date
for i in {{1..{nruns}}}
do
  rm RunWeb
  ./bin/generate_events -f --laststep=delphes
  ./bin/madevent remove all parton -f
  ./bin/madevent remove all pythia -f
done
date
echo "DONE"
exit 0
